# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('population', models.IntegerField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Статистика',
                'verbose_name': 'Статистика',
            },
        ),
    ]
